package com.melodyrent.service;
import com.melodyrent.dto.AuthDtos.*; import com.melodyrent.entity.*; import com.melodyrent.exception.ApiException; import com.melodyrent.repository.*; import com.melodyrent.security.JwtService; import lombok.RequiredArgsConstructor; import org.springframework.http.HttpStatus; import org.springframework.security.authentication.*; import org.springframework.security.core.userdetails.UserDetailsService; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import java.util.stream.Collectors;
@Service @RequiredArgsConstructor
public class AuthService {
  private final UserRepository users; private final RoleRepository roles; private final PasswordEncoder encoder; private final AuthenticationManager authManager; private final JwtService jwt; private final UserDetailsService userDetails;
  public AuthResponse register(RegisterRequest req){ if(users.existsByEmail(req.email())) throw new ApiException(HttpStatus.CONFLICT,"Email already registered"); var roleNames=req.roles()==null||req.roles().isEmpty()? java.util.Set.of(RoleName.CUSTOMER):req.roles(); var roleSet=roleNames.stream().map(r -> roles.findByName(r).orElseGet(() -> roles.save(Role.builder().name(r).build()))).collect(Collectors.toSet()); var u=users.save(User.builder().fullName(req.fullName()).email(req.email()).password(encoder.encode(req.password())).roles(roleSet).build()); var details=userDetails.loadUserByUsername(u.getEmail()); return response(u, jwt.accessToken(details), jwt.refreshToken(details)); }
  public AuthResponse login(LoginRequest req){ authManager.authenticate(new UsernamePasswordAuthenticationToken(req.email(), req.password())); var u=users.findByEmail(req.email()).orElseThrow(); var details=userDetails.loadUserByUsername(u.getEmail()); return response(u, jwt.accessToken(details), jwt.refreshToken(details)); }
  private AuthResponse response(User u,String access,String refresh){ return new AuthResponse(access, refresh, "Bearer", new UserSummary(u.getId(),u.getFullName(),u.getEmail(),u.getRoles().stream().map(r->r.getName().name()).collect(Collectors.toSet()),u.getRewardPoints(),u.getLevel().name())); }
}
