package com.melodyrent.service;
import com.melodyrent.dto.BookingDtos.*; import com.melodyrent.entity.*; import com.melodyrent.exception.ApiException; import com.melodyrent.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.http.HttpStatus; import org.springframework.messaging.simp.SimpMessagingTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.List;
@Service @RequiredArgsConstructor
public class BookingService {
  private final BookingRepository bookings; private final UserRepository users; private final ProductService productService; private final PricingService pricing; private final SimpMessagingTemplate ws;
  public PriceQuote quote(BookingRequest req){ return pricing.quote(productService.entity(req.productId()), req.startDate(), req.endDate()); }
  @Transactional public BookingResponse book(BookingRequest req, String email){ var user=users.findByEmail(email).orElseThrow(); var product=productService.entity(req.productId()); if(bookings.overlaps(product.getId(), req.startDate(), req.endDate())) throw new ApiException(HttpStatus.CONFLICT,"Product is unavailable for the selected dates"); var quote=pricing.quote(product, req.startDate(), req.endDate()); var b=bookings.save(Booking.builder().customer(user).product(product).startDate(req.startDate()).endDate(req.endDate()).totalPrice(quote.totalPrice()).status(BookingStatus.CONFIRMED).build()); user.setRewardPoints(user.getRewardPoints()+50); user.setLevel(level(user.getRewardPoints())); ws.convertAndSend("/topic/availability", java.util.Map.of("productId", product.getId(), "status", "BOOKED")); ws.convertAndSend("/topic/notifications/"+user.getId(), java.util.Map.of("title", "Booking confirmed", "message", product.getTitle()+" is yours!")); return toResponse(b); }
  public List<BookingResponse> mine(String email){ var u=users.findByEmail(email).orElseThrow(); return bookings.findByCustomerIdOrderByCreatedAtDesc(u.getId()).stream().map(this::toResponse).toList(); }
  private GamificationLevel level(int points){ if(points>=2500) return GamificationLevel.VIP; if(points>=1000) return GamificationLevel.ADVENTURER; if(points>=250) return GamificationLevel.EXPLORER; return GamificationLevel.BEGINNER; }
  private BookingResponse toResponse(Booking b){ return new BookingResponse(b.getId(), b.getProduct().getId(), b.getProduct().getTitle(), b.getStartDate(), b.getEndDate(), b.getTotalPrice(), b.getStatus().name()); }
}
